Gemfile
Gemfile.lock
README.md
app/controllers/api/trips_controller.rb
app/models/trip.rb
app/models/user.rb
app/serializers/trip_serializer.rb
config/routes.rb
test/controllers/api/trips_controller_test.rb

Introduce a My Trips API endpoint for a given rider
They can get information about their own trips. Adopt the JSON API spec to spec out the API details.

Feat fast jsonapi

---

Gemfile
Gemfile.lock
app/controllers/api/trips_controller.rb
app/controllers/api_controller.rb
app/controllers/authentication_controller.rb
app/models/user.rb
config/application.rb
config/routes.rb
db/migrate/20200603150442_add_column_users_password_digest.rb
db/schema.rb
lib/json_web_token.rb
test/controllers/api/trips_controller_test.rb
test/controllers/authentication_controller_test.rb
test/fixtures/riders.yml
yarn.lock

Add user password authentication
Use Active Model has_secure_password
Add password_digest column to User model
Confirm password confirmation validation in
rails console by creating some users with
and without it
JWT gem was added here as well as that is part
of future commits on this PR
Add authentication controller
If the user is authenticated, respond with a
JSON web token, otherwise an authorized response
Here are some example curl requests exported from Postman:
```
~/Projects/rideshare (api-auth-jwt) $ curl -s --location --request POST 'http://localhost:3000/auth/login' --form 'email=usercool3@example.com' --form 'password=abcd1234' | jq
{
"token": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMTYsImV4cCI6MTU5MTI4NTUyM30.Qo-1bBnZYN4sayW6zQ7MfcigU_8JN_X2_iMthqHIm6Q",
"exp": "06-04-2020 …
```

Api auth jwt

---

Gemfile.lock

Bump rails version

---

README.md
app/models/trip_request.rb
app/models/vehicle.rb
app/models/vehicle_reservation.rb
app/services/book_reservation.rb
config/application.rb
db/migrate/20220729014635_create_vehicle_reservations.rb
db/migrate/20220729020430_create_vehicles.rb
db/migrate/20220801140121_add_exclusion_constraint_vehicle_registrations.rb
db/schema.rb
db/structure.sql
scripts/book_reservations.sh
test/fixtures/locations.yml
test/fixtures/trip_requests.yml
test/fixtures/trips.yml
test/fixtures/vehicle_reservations.yml
test/fixtures/vehicles.yml
test/models/vehicle_reservation_test.rb
test/models/vehicle_test.rb
test/services/book_reservation_test.rb

Add a service class that creates the reservation. A reservation is
attached to the trip request model, but means that a trip request can
involve a reserved special vehicle, like a party bus.
Add another NYC location to create a local NYC travel itinerary, "girls
night out". Add Comedy Cellar. :)
Add a test for the service class to make sure the reservation is created
correctly. Add basic model validations and basic test coverage.

Add vehicle reservations

---

lib/tasks/data_generators.rake
scripts/dump_users_table.sh
scripts/load_users_table.sh

Add separate pg_dump and psql load shell scripts to dump and load large
amounts of user data for the purposes of working with the scrubber
functions

Use bulk loading of User records

---

scripts/scrubbing/constraints_external_add_back.sql
scripts/scrubbing/create_tables.sql
scripts/scrubbing/drop_and_swap_users.sql
scripts/scrubbing/generate_add_constraint_external_tables.sql
scripts/scrubbing/generate_add_constraint_statements.sql
scripts/scrubbing/scrub_users.sql
scripts/scrubbing/scrubber.sh

Automate the process of producing a scrubbed set of tables

Scrubbing script

---

config/database.yml
docker-compose.dev.yml
docker-compose.test.yml

Add required POSTGRES_PASSWORD for SUPERUSER role, update database.yml

---

config/database.yml
docker-compose.dev.yml
docker-compose.test.yml

Reverts andyatkinson/rideshare#100

Revert "Revert "Add required POSTGRES_PASSWORD for SUPERUSER role, update database.yml""

---

config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

Opt out of Active Storage and other frameworks that aren't needed

Reduce frameworks

---

lib/tasks/benchmarks.rake
lib/tasks/custom.rake

Compare Active Record methods
Fix the task description for a unrelated task

Add benchmark for memory usage

---

postgresql/README.md
postgresql/pgbouncer.sample.ini

Better general recommendation
Linked excellent article showing feature incompatibilities with
transaction and statement pooling modes

Add docs on transaction pooling mode

---

config/database-multiple.sample.yml
db/env_vars_sample.sh

Use "rideshare" for the primary, and "rideshare_replica" for the replica
The "Scaling With Replication And Sharding" chapter covers how to set up
db01 and db02 primary and replica instances using Docker.

Update multiple DBs sample configuration

---

Gemfile
Gemfile.lock

Use the The Pessimistic Version Operator
https://devalot.com/articles/2012/04/gem-versions.html
Use some forks
For some gems, we can run whatever the latest version is

Reviewer suggestion: Add minor version

---

.env
GUIDES.md
Gemfile
Gemfile.lock
README.md
db/create_grants_schema.sql
db/create_role_owner.sql
db/setup.sh

Simplify the instructions further
Incorporate more feedback from @danielabar

Improve README. Thanks @danielabar

---

README.md
db/README.md

Break out some book content that didn't quite fit, into a section here
in the app

Add db/README.md

---

postgresql/pgbouncer.sample.ini
postgresql/userlist.sample.txt

Add sample userlist.txt file

---

docker/db01_create_replication_user.sh

Check that db01 and db02 are running first

---

.env
Gemfile.lock
docker/teardown_docker.sh
dump_rideshare_local_to_db01.sh
postgresql/.pgpass.sample

Updates on documentation and scripts

---

docker/run_pg_basebackup.sh

Run commands as one

---

config/database-slow-clients.sample.yml
db/README.md

- Slow clients sample DB config
- Add README use case

Sample DB Slow Client configuration block

---

db/README.md
postgresql/postgresql.sample.conf

Add sample config file
Add screenshot showing pg_cron scheduled jobs in action with PgHero

PgHero Scheduled Jobs with pg_cron writeup

---

app/models/location.rb
app/models/trip_position.rb
app/models/user.rb
app/models/vehicle.rb
db/README.md

Identified various consistency improvements between Active Record and
database constraints
Added instructions on how to run this tool

Checking out database_consistency report

---

db/scrubbing/README.md
db/scrubbing/scrub_batched_direct_updates.sql

Add procedure that does batched updates

Add procedure example

---

.env
Gemfile.lock
db/README.md

Set custom schema via an environment variable
Add some usage documentation

Update rails-pg-extras, use custom schema

---

lib/tasks/data_generators.rake

- Set a drivers_license_number for all Drivers

Fix data generators task

---

db/scripts/bulk_load.sh

Add lines to help load greater numbers to reach 50 million rows, by
uncommenting the commented out lines with new sequence ranges
This could be parameterized in the future

Bulk load script

---

docker/run_pg_basebackup.sh
docs/workshop/6_macro_overview_part_1.md
docs/workshop/7_macro_overview_part_2.md
docs/workshop/README.md

Improving the workshop quality based on things that didn't go smoothly.
Add notes about creating the docker network

Post-workshop updates

---

docs/design_document.md
docs/project_documentation.md
docs/workshop/7_macro_overview_part_2.md
lib/tasks/simulate_app_activity.rake

👋 Thanks for getting this repo out along with a great book!
- While reading through the docs I thought it would be nice to match the latest Rails version that matches the gemfile `'~> 7.1'`.  😊
- Also corrected a few typos that I bumped into it.

[Docs and Readme] Point to correct Rails version docs matching the Gemfile
